config/routes.rb
Rails.application.routes.draw do
  
  get 'items/new'

  resources :lists, except: [:index] do
    resources :items, only: [:create, :destroy]
  end
  
  get 'items/clear' => 'items#clear', :as => :clear_items

  root to: 'welcome#index'
  
  get 'about' => 'welcome#about'

  devise_for :users
  
  
  
  
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  
  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end
  
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_one :list, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :js
  
  def create
    @list = current_user.list
    @item = Item.new(item_params)
    @item.list = @list
    
    if @item.save
      # flash[:notice] = "Item added successfully!"
    else
      # flash[:error] = "Item was not added successfully. Please try again."
    end
    
    respond_with(@item) do |format|
      format.html { redirect_to list_path(@list) }
    end
  end
  
  def clear
    @list = current_user.list
    @list.items.destroy_all
    
    redirect_to list_path(@list)
  end
  
  def destroy
    @list = current_user.list
    @item = Item.find(params[:id])
    
    if @item.destroy
      # flash[:notice] = "To-Do item completed!"
    else
      # flash[:error] = "There was an error completing this item. Please try again."
    end 
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name)
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user! # Users must be signed in for the methods to work
  
  def show
    @list = current_user.list
    @items = current_user.list.items
  end

  def new
    create
  end
  
  def create
    @list = List.new(user: current_user, title: "My To-Do List")
    @list.save
    go_back_to_list
  end

  def edit
    @list = current_user.list
  end
  
  def update
    @list = current_user.list
    
    if @list.update_attributes(list_params)
      flash[:notice] = "To-Do List updated successfully!"
      go_back_to_list
    else
      flash[:error] = "There was an error updating the To-Do List. Please try again."
      render :edit
    end
  end
  
  def destroy
    @list = current_user.list
    
    if @list.destroy
      flash[:notice] = "To-Do List deleted successfully"
      redirect_to root_path
    else
      flash[:error] = "There was an error deleting the To-Do List. Please try again."
      go_back_to_list
    end
  end
  
  private
  
  def list_params
    params.require(:list).permit(:title)
  end
  
  def go_back_to_list
    redirect_to list_path(@list)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_clear.html.erb
<%= link_to "Clear List", clear_items_path, class: 'btn btn-default btn-list-nudge', data: { confirm: 'Are you sure you want to clear this list?' } %>

app/views/items/_form.html.erb
<%= form_for [list, list.items.new] do |f| %>
  <div class="form-group">
    <%= f.label "New To-Do Item:" %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'What do you need to do?' %>
  </div>

  <div class="form-group">
    <%= f.submit "Add", class: 'btn btn-default' %>
  </div>
<% end %>    

app/views/items/_item.html.erb
<tr id="item-<%= item.id %>">
  <td class="width-percent-60">
    <%= item.name %>
  </td>
  <td class="width-percent-20">
    <small><%= item.days_left %></small>
  </td>
  <td class="width-percent-20">
    <small><%= link_to "", [list, item], method: :delete, class: "glyphicon glyphicon-ok", remote: true %></small>
  </td>
</tr>

app/views/items/create.js.erb
// add jquery to append the new item to the bottom of the table?

app/views/items/destroy.js.erb
$('#item-' +<%= @item.id %>).hide();

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    
    <!-- nav area -->
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if current_user %>
        <li>
          <% if current_user.list.nil? %>
            <%= link_to ">>> Let's Get Started! <<<", new_list_path %>
          <% else %>
            <%= link_to "To-Do List", list_path(current_user.list) %>
          <% end %>
        </li>
      <% end %>
      
      <div class="pull-right user-info">   
        <% if current_user %>
        Hello <%= link_to (current_user.email), edit_user_registration_path %> |
          <%= link_to "Sign out?", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
      
    </ul>
    
    <!-- display flash messages -->
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
    
  </div>

</body>
</html>

app/views/lists/edit.html.erb
<h1>Edit To-Do List</h1>

<div class="row">
  <div class="col-md-6">
    
    <%= form_for @list do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: @list.title %>
      </div>
    
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-default' %>
      </div>
    <% end %>
  
  </div>
</div>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Setup To-Do List</h1>

<div class="row">
  <div class="col-md-6">
    
    <%= form_for @list do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter To-do List Title' %>
      </div>
    
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-default' %>
      </div>
    <% end %>
  
  </div>
</div>

app/views/lists/show.html.erb
<% if @list.nil? %>
  <%= link_to "Set up your To-Do List", new_list_path, class: 'btn btn-default' %>
<% else %>

<div class="row">
  <div class="col-md-12">
    <h1> 
      <%= @list.title %>
      <%= link_to "Edit List", edit_list_path, class: 'btn btn-default btn-list-nudge' %> 
      <%= render partial: 'items/clear' %>
    </h1> 
    
    <%= render partial: "items/form", locals: { list: @list } %>
    
    <table class="table table-striped">
      <thead>
        <tr>
          <td>
            <strong>To-Do Item</strong>
          </td>
          <td>
            <strong>Days Left</strong>
          </td>
          <td>
            <strong>Complete?</strong>
          </td>
        </tr>
      </thead>
      <tbody id="item-table">
  
        <% @items.each_with_index do |item, index| %>
          <% unless index >= @items.count %>
            <%= render partial: "items/item", locals: { item: item, list: @list} %>
          <% end %>
        <% end %>
  
      </tbody>
    </table>

  </div>
</div>

<% end %>
    

app/views/welcome/about.html.erb
<div class="row">
  <div class="col-md-12">
    
    <br/>
    <div class="jumbotron">
      <h1>Why Blocitoff?</h1>
      <p>To-Do lists are notorious for collecting junk: to-do items that you want to remember, but are not very important and thus consistently get put-off. To address this problem of to-do list clutter, we've created Blocitoff.</p>
      <p>This app will help you keep to-do lists manageable by automatically deleting items that have not been completed after seven days. Our belief is that if the to-do item is not important enough to be completed in seven days, it doesn't belong on your to-do list.</p>
      
      <% if current_user %>
      
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-info btn-lg' %>  
          &nbsp
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info btn-lg' %>  
      <% end %>
    </div>  
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12">
    
    <br/>
    <div class="jumbotron">
      <h1 class="glyphicon glyphicon-list-alt pull-left"></h1>
      <h1>&nbspBlocitoff</h1>
      <p>The really awesome To-Do app!</p>
      <%= link_to "Learn more", about_path, class: 'btn btn-info btn-lg' %>
    </div>  
  </div>
</div>